[package]
name = "async-bincode"
version = "0.5.0-alpha.3"
edition = "2018"

description = "Asynchronous access to a bincode-encoded item stream."
readme = "README.md"

authors = [
	"Jon Gjengset <jon@thesquareplanet.com>",
	"Jonathan Behrens <behrensj@mit.edu>"
]

homepage = "https://github.com/jonhoo/async-bincode"
repository = "https://github.com/jonhoo/async-bincode.git"

keywords = ["asynchronous", "tokio", "bincode", "serialization"]
categories = ["asynchronous", "encoding", "network-programming"]

license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "jonhoo/async-bincode" }
maintenance = { status = "passively-maintained" }

[dependencies]
bincode = "1.0.0"
byteorder = "1.0.0"
futures-core-preview = "0.3.0-alpha.18"
futures-sink-preview = "0.3.0-alpha.18"
serde = "1.0.8"
tokio-io = "0.2.0-alpha.4"
#tokio-io = { git = "https://github.com/tokio-rs/tokio.git" }
bytes = "0.4.11"

[dev-dependencies]
futures-preview = "0.3.0-alpha.18"
tokio = "0.2.0-alpha.4"
#tokio = { git = "https://github.com/tokio-rs/tokio.git" }
